name: salud_a_un_cilc
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Gabriel Castanaza <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  redux: 3.0.0
  test: 1.6.3
